spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      secret: JOwmxZ10Mid8CDzXmelthjFvddbWKImO
      expiration: 30000 #1 day
      refresh-token:
        expiration: 604800000 #7 days